#!/bin/bash
#PBS -A open
#PBS -l walltime=47:00:00
#PBS -l nodes=1:ppn=7
#PBS -l pmem=32gb
#PBS -j oe
#PBS -m abe
#PBS -M anthony.e.wong@colorado.edu

##R --vanilla < /storage/home/a/axw322/work/codes/GEOCARB/R/GEOCARB_calib_driver_script_unc.R > /storage/home/a/axw322/work/codes/GEOCARB/R/rgeocarb_mcmc_unc.log
R --vanilla < /storage/home/a/axw322/work/codes/GEOCARB/R/GEOCARB_calib_driver_script_mixture.R > /storage/home/a/axw322/work/codes/GEOCARB/R/rgeocarb_mcmc_unc.log
